version: '3.8'

services:
  db:
    image: postgres:15
    container_name: avito-shop-db
    restart: always
    environment:
      POSTGRES_DB: avito_shop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: avito-shop-app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: avito_shop
    command: ["/app/main"]

volumes:
  pg_data:
